pipeline {
    agent {
        kubernetes {
          yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: jworker
                image: gmldba/jenkins_worker:latest
                command:
                - "/bin/sh"
                - "cat"
                tty: true
          '''
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'python3 version"'
            }
        }
    }
}