pipeline {
    agent {
        kubernetes {
          yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: jworker
                image: gmldba/python_w:latest
                command:
                - /bin/sh
                - -c
                - 'while true; do sleep 10; done'
                tty: true
          '''
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'echo "Hello World!"'
            }
        }
    }
}